enableGlobalCache: true

enableTelemetry: false

npmRegistryServer: "https://registry.npmjs.org"

nodeLinker: node-modules

supportedArchitectures:
  cpu:
    - x64
    - arm64
  libc:
    - glibc
    - musl
  os:
    - darwin
    - linux

yarnPath: .yarn/releases/yarn-4.6.0.cjs