[profile.default]
src = "src"
out = "out"
libs = ["node_modules"]
allow_paths = ["node_modules"]
fs_permissions = [{ access = "read-write", path = "./" }]

optimizer = true
optimizer_runs = 200

[etherscan]
optimism = { key = "${OPTIMISTIC_ETHERSCAN_API_KEY}" }
optimism-sepolia = { key = "${OPTIMISTIC_ETHERSCAN_API_KEY}" }
mainnet = { key = "${ETHERSCAN_API_KEY}" }
sepolia = { key = "${ETHERSCAN_API_KEY}" }
