exports.address = '0x02aDE328C6177659F16FCdE5E3beA32e47922971';
exports.abi = [
  'constructor(address defaultAdmin)',
  'function DEFAULT_ADMIN_ROLE() view returns (bytes32)',
  'function GRANTED() view returns (bytes32)',
  'function PENDING() view returns (bytes32)',
  'function approveApplication(address user)',
  'function getRoleAdmin(bytes32 role) view returns (bytes32)',
  'function grantRole(bytes32 role, address account)',
  'function hasRole(bytes32 role, address account) view returns (bool)',
  'function isAdmin(address user) view returns (bool)',
  'function isGranted(address user) view returns (bool)',
  'function isPending(address user) view returns (bool)',
  'function rejectApplication(address user)',
  'function renounceRole(bytes32 role, address callerConfirmation)',
  'function revokeRole(bytes32 role, address account)',
  'function submitApplication()',
  'function supportsInterface(bytes4 interfaceId) view returns (bool)',
  'function transferOwnership(address newOwner)',
  'function withdrawApplication()',
  'event RoleAdminChanged(bytes32 indexed role, bytes32 indexed previousAdminRole, bytes32 indexed newAdminRole)',
  'event RoleGranted(bytes32 indexed role, address indexed account, address indexed sender)',
  'event RoleRevoked(bytes32 indexed role, address indexed account, address indexed sender)',
  'error AccessControlBadConfirmation()',
  'error AccessControlUnauthorizedAccount(address account, bytes32 neededRole)',
];
